## **Fancy Indexing (Masking)**

- Numpy arrays can be indexed with boolean arrays (masks).
- This method is called **fancy indexing** or **masking**.

\
What would happen if we do this?


In [ ]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

**Comparison operation also happens on each element**.
- All the values before 6 return `True`
- All the values after 6 return `False`



**Question:** What will be the output of the following?

In [ ]:
m1[[True,  True,  True,  True,  True, False, False, False, False, False]]

array([1, 2, 3, 4, 5])

Notice that we are passing a list of indices.
- For every instance of `True`, it will print the corresponding index.
- Conversely, for every `False`, it will skip the corresponding index, and not print it.

So, this becomes a **filter** of sorts.

Now, let's use this to filter or mask values from our array.

**Condition will be passed instead of indices and slice ranges.**

In [ ]:
m1[m1 < 6]

array([1, 2, 3, 4, 5])

This is known as **Fancy Indexing** in Numpy.

\
**Question:** How can we filter/mask even values from our array?

In [ ]:
m1[m1%2 == 0]

array([ 2,  4,  6,  8, 10])

---

## **Fancy Indexing (Masking) in 2D arrays**

We did this for one dimensional arrays. Let's see if those concepts translate to 2D also.

\
Suppose we have the matrix `m1` -

In [ ]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**What will be output of following?**

In [ ]:
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

- A **matrix having boolean values** `True` and `False` is returned.
- **We can use this boolean matrix to filter our array.**

\
**Condition(s) will be passed instead of indices and slice ranges.**

In [ ]:
m1[m1 < 6]

array([0, 1, 2, 3, 4, 5])

- Values corresponding to `True` are retained
- Values corresponding to `False` are filtered out

---